### ISSUE TITLE
Aimbot not working after April fools update

### ISSUE THREAD

**Issue by FlovereX** [MOTwrrt/RushPoint-cheat#1]
Hey there! I really like your Script! There's just a problem and that is aimbot doesn't work for some reason... or i got something wrong. If you can fix that, that'll be great! Thanks!!

**Comment by MOTwrrt** [comment]
Hey! Sorry for the 2 weeks late response but it's still working fine for me, I think it's something with your settings
https://streamable.com/u5nb04
